### ISSUE TITLE
Look into using MS BotBuilder

### ISSUE THREAD

**Issue by findel** [findel/spype#1]
This could be used to replace skyweb and/or add functionality for slack. 

https://github.com/Microsoft/BotBuilder

**Comment by JuniorGenius** [comment]
Yes. PLEASE. As of now, it's useless until you do this.

**Comment by findel** [comment]
It's not "useless" really, folks are using it! 

As it turns out BotBuilder will be no good for Spype. Bots built with BotBuilder will not suppot the features that Spype needs. For example; Although you can add BotBuilder Bots to group chats in Skype, they will only receive messages directed at them. 

Spype needs to be able to read ALL messages. 

So this is a no go at the moment.

**Comment by JuniorGenius** [comment]
Well, the only other solution is to fix skyweb to use live accounts. And by useless I mean that no one can use it unless they have an extra Skype account with the correct name that they made years ago that they don't need to use. I find it hard to imagine many people do at this point.

**Comment by findel** [comment]
Turns out the Bot Framework will be of no use to Spype, since they only support the scenario where the bot reads and replies to messages directed at the bot. I can't sit in a group chat and parse all of the messages. 

I'll close this for now.
